print("**************************calculator************************")
print("\n")

a=int(input("ENTER THE FIRST NUMBER HERE:-"))
print("\n")
b=int(input("ENTER THE SECOND NUMBER HERE:-"))
print("\n")
print("select operation")
print("\n")
print("1.addition")
print("2.subraction")
print("3.multiplication")
print("4.division")
print("5.exponential")
print("6.modulus")
print("7.floor division")
print("8.exit")
print("\n")
choice=int(input("enter choice(1/2/3/4/5/6/7/8):"))
print("\n")
if choice==8:print("goodbye")
elif choice==1:print("addition of two number is ",a+b)
elif choice==2:print("subraction of two number is ",a-b)
elif choice==3:print("multiplication of two number is ",a*b)
elif choice==4:print("division of two number is ",a/b)
elif choice==5:print("exponential of two number is ",a**b)
elif choice==6:print("modulus of two number is ",a%b)
elif choice==7:print("floor division of two number is ",a//b)
else : print("invalid input")
print("\n")
print("thank you")
